name: Build

on:
  workflow_call:

jobs:
  build:
    name: Go Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - uses: actions/checkout@v3
      - run: go build ./...
