name: Go API Workflow CI

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Go Test
      uses: ./.github/workflows/test.yml
    - name: Lint
      uses: ./.github/workflows/lint.yml
    - name: Analyze
      uses: ./.github/workflows/codeql.yml
  build:
    runs-on: ubuntu-latest
    name: Build Image
    uses: calebtracey/devops/templates/.github/workflows/build.yml
    needs: [ test, lint, analyze ]
  push:
    runs-on: ubuntu-latest
    name: Push Image
    uses: calebtracey/devops/templates/.github/workflows/push.yml
    needs: build
