name: Go API Workflow CI

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Go Test
      uses: ./.github/actions/test.yml
    - name: Lint
      uses: ./.github/actions/lint.yml
    - name: Analyze
      uses: ./.github/actions/codeql.yml
  build:
    runs-on: ubuntu-latest
    name: Build Image
    uses: ./.github/actions/build.yml
    needs: [ test, lint, analyze ]
  push:
    runs-on: ubuntu-latest
    name: Push Image
    uses: ./.github/actions/push.yml
    needs: build
